### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position 558

### ISSUE THREAD

**Issue by pawelotto** [zk1169/tspath#1]
Doesn't work at all.
Node version v10.5.0

`
undefined:55
    },
    ^

SyntaxError: Unexpected token } in JSON at position 558
    at JSON.parse (<anonymous>)
    at ParserEngine.readConfig (/usr/lib/node_modules/tspath-fixed/dist/src/parser-engine.js:214:30)
    at ParserEngine.execute (/usr/lib/node_modules/tspath-fixed/dist/src/parser-engine.js:90:36)
    at TSPath.processPath (/usr/lib/node_modules/tspath-fixed/dist/src/tspath.js:39:25)
    at Confirm.callback (/usr/lib/node_modules/tspath-fixed/dist/src/tspath.js:29:27)
    at Confirm.<anonymous> (/usr/lib/node_modules/tspath-fixed/node_modules/prompt-base/index.js:625:10)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
`

**Comment by zk1169** [comment]
It seems that content in tsconfig.json is not json string.
Please check your tsconfig.json file first.
